cmake_minimum_required (VERSION 4.0)
project("Snake")




#------------------------------------------------------------------------------
# Сборка исполняемого файла
#------------------------------------------------------------------------------
add_executable(Snake src/main.c)




#------------------------------------------------------------------------------
# Подключение библиотеки потоков в зависимости от ОС
#------------------------------------------------------------------------------
if(WIN32)
	find_package(PThreads4W CONFIG REQUIRED)
	target_link_libraries(Snake PRIVATE PThreads4W::PThreads4W)
else()
	# Для Linux - линкуем pthread напрямую
	target_link_libraries(Snake PRIVATE pthread)
endif()




#------------------------------------------------------------------------------
# настройки компилятора
#------------------------------------------------------------------------------
set_property(TARGET Snake PROPERTY C_STANDARD 99)




#------------------------------------------------------------------------------
# настройки предупреждений компилятора (опционально)
#------------------------------------------------------------------------------
#include(Warnings.cmake)
